### ISSUE TITLE
WPTProfiler warnings/errors

### ISSUE THREAD

**Issue by pupnewfster** [Artem226/MinecraftEcologyMod#22]
As requested I am posting some of the bugs we are having. The main one is that after a little exploring (rather quickly given we have iblis which lets you train up move speed) we get console spam about "[Ecology Mod]: {"air" : 0.0, "water" : 0.0, "soil" : 0.0}". This is not the reason I removed the mod as I am assuming it is just a debug message, however it seems odd that new chunks would have to be checked for pollution and that if it is how do you do it so you do not have to check every block in each new chunk. I have since removed a couple other mods from my test version of the pack (Vampirism and MusicCraft) because they were showing up with https://minecraft.curseforge.com/projects/worldgeneration-profiler as often taking longer than they should to generate chunks.

I decided to test in single player as requested to try and find some examples of the errors we have. (I have yet to just start timing out indefinitely, though that may just be because of how singleplayer works). I did however get these warnings https://pastebin.com/35BLJv1H about WPTProfiler taking longer than usual and about this mod causing cascading worldgen lag.

I also have crashed once since the last update to the WPTProfiler with a ConcurrentModificationException, (if memory serves it was not one to do with entities like #15 that seems to have been fixed), but I am unable to find the logs to copy it. I did not save it initially as I figured it was just a fluke error that might have been caused by the server lagging and that it would happen again, hopefully when I was actually on so that I could see what might have caused it.

Forge Version: 14.23.1.2585
EcologyMod version: 1.12.2-1.3.0.0

**Comment by pupnewfster** [comment]
Actually before closing my single player world I decided to test for another minute or so and got the same error as in #15.
```java
[14:07:40] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:290) ~[ol.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:777) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Thank you for your issue and information. But if you get a crash report, could you please send its section about the world processing threads? Like this :[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 	Kep_0: Working: true |Last Profiler section: WPT_DO_DIFFUSION| Interrupted:false

It can help me to determine the circumstances of the error. 

And about that message, it is really a debug message, which I forgot to remove.

**Comment by pupnewfster** [comment]
The crash report with the ConcurrentModificationException has at the bottom
`[EcologyMod|PollutionHandler] Active WorldProcessingThreads: 
	New World_0: Working: true |Last Profiler section: WPT_CALCULATING_CHUNK_POLLUTION| Interrupted:false`

When it warned me about `[13:51:49] [WPT_0/WARN] [FML]: Ecology Mod loaded a new chunk (-181, -100  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.` It did not crash so I cannot include what processing threads or things caused it.

**Comment by Artem226** [comment]
Thanks.) I hope that It will be fixed soon.

**Comment by Artem226** [comment]
Thanks.) I hope that It will be fixed soon.

**Comment by Artem226** [comment]
Hello, @pupnewfster! Could you test the new version as it became available?

**Comment by pupnewfster** [comment]
Hi, @Artem226 I received this in my log, while flying around trying to test. I do not have anything in a crash report as my game/singleplayer world did not crash. I will keep flying around a little to see if I can get the entity crash to occur. (Hopefully it is fixed)

```java
[11:19:25] [WPT_0/INFO] [Ecology Mod]: Starting world processing... (dim 0)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: java.util.ConcurrentModificationException
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at java.util.ArrayList$Itr.next(Unknown Source)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at ecomod.common.pollution.handlers.PollutionHandler.onWorldTickTiles(PollutionHandler.java:370)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_964_PollutionHandler_onWorldTickTiles_WorldTickEvent.invoke(.dynamic)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:285)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[11:19:25] [Server thread/INFO] [STDERR]: [ecomod.common.pollution.handlers.PollutionHandler:onWorldTickTiles:435]: 	at java.lang.Thread.run(Unknown Source)
[11:19:25] [WPT_0/INFO] [Ecology Mod]: Serializing and saving pollution manager for dimension 0
[11:19:25] [WPT_0/INFO] [Ecology Mod]: World processing completed in 0.137 seconds
```

**Comment by pupnewfster** [comment]
This appears to be fixed so I am closing the issue.
